#spring:
#  datasource:
#    username: root
#      password: Prit@411
#        url: jdbc:mysql://localhost:3306/crudoperation
#          driver-class-name: com.mysql.cj.jdbc.Driver
#       jpa:
#         show-sql: true
#         hibernate:
#           ddl-auto: update
#           properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#

